gradebook/gradebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gradebookprj.urls'))
]

gradebook/gradebookprj/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('admin_dash/', admin_dash, name='admin_dash'),
    path('teacher_dash/', teacher_dash, name='teacher_dash'),
    path('student_dash/', student_dash, name='student_dash'),
    path('parent_dash/', parent_dash, name='parent_dash'),
    path('logout/', logout_user, name='logout'),
    path('create_subject/', create_subject, name='create_subject'),
    path('get_subjects/', get_subjects, name='get_subjects'),
    path('get_classes/', get_classes, name='get_classes'),
    path('get_parents/', get_parents, name='get_parents'),
    path('schedule/', schedule_edit, name='schedule'),
    path('rate/<int:subject_id>/<int:class_id>/', rate_view, name='rate'),
]

gradebook/gradebookprj/models.py
from django.db import models


class Class(models.Model):
    class_id = models.AutoField(primary_key=True)
    class_name = models.CharField(max_length=255)

    def __str__(self):
        return self.class_name

class Subject(models.Model):
    subject_id = models.AutoField(primary_key=True)
    subject_name = models.CharField(max_length=255)

    def __str__(self):
        return self.subject_name

class Teacher(models.Model):
    teacher_id = models.AutoField(primary_key=True)
    full_name = models.CharField(max_length=255)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    phone_number = models.IntegerField()
    email = models.EmailField()

    def __str__(self):
        return self.full_name

class Parent(models.Model):
    parent_id = models.AutoField(primary_key=True)
    full_name = models.CharField(max_length=255)
    phone_number = models.IntegerField()
    email = models.EmailField()

    def __str__(self):
        return self.full_name

class Student(models.Model):
    student_id = models.AutoField(primary_key=True)
    full_name = models.CharField(max_length=255)
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE)
    birth_date = models.DateField()
    phone_number = models.IntegerField()
    email = models.EmailField()
    parent_id = models.ForeignKey(Parent, on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name

class Grade(models.Model):
    grade = models.IntegerField()
    subject_id = models.ForeignKey(Subject, on_delete=models.CASCADE)
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)

class Schedule(models.Model):
    schedule_id = models.AutoField(primary_key=True)
    subject_id = models.ForeignKey(Subject, on_delete=models.CASCADE)
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE)
    teacher_id = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return f"{self.subject_id} - {self.class_id} - {self.teacher_id} - {self.date}"

gradebook/gradebookprj/forms.py
from django import forms
from .models import *

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password', 'role']
        widgets = {
            'password': forms.PasswordInput(),
        }

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['subject_name']

class ClassesForm(forms.ModelForm):
    class Meta:
        model = Classes
        fields = ['class_name']

class TeacherRegistrationForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['full_name', 'subject', 'phone_number', 'email']

class StudentRegistrationForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['full_name', 'class_id', 'birth_date', 'phone_number', 'email', 'parent_id']

class ParentRegistrationForm(forms.ModelForm):
    class Meta:
        model = Parent
        fields = ['full_name', 'phone_number', 'email']

class GradeForm(forms.ModelForm):
    class Meta:
        model = Grade
        fields = ['grade', 'date', 'student_id']

    def __init__(self, *args, **kwargs):
        class_id = kwargs.pop('class_id', None)
        super(GradeForm, self).__init__(*args, **kwargs)
        if class_id:
            self.fields['student_id'].queryset = Student.objects.filter(class_id=class_id)

gradebook/gradebookprj/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from functools import wraps
from django.http import HttpResponseForbidden, JsonResponse

def role_required(role):
    def decorator(view_func):
        @wraps(view_func)
        def wrapper(request, *args, **kwargs):
            if request.user.is_authenticated and request.user.role == role:
                return view_func(request, *args, **kwargs)
            else:
                return HttpResponseForbidden("Access is denied")
        return wrapper
    return decorator

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.role == 'admin':  # Проверка, является ли пользователь администратором
                return redirect('admin_dash')  # Перенаправление на страницу администратора
            elif user.role == 'teacher':  # Проверка, является ли пользователь учителем
                return redirect('teacher_dash')  # Перенаправление на страницу учителя
            elif user.role == 'student':  # Проверка, является ли пользователь студентом
                return redirect('student_dash')  # Перенаправление на страницу студента
            elif user.role == 'parent':  # Проверка, является ли пользователь родителем
                return redirect('parent_dash')  # Перенаправление на страницу родителя
            else:
                return redirect('home')  # Перенаправление на главную страницу для всех остальных ролей
        else:
            messages.error(request, 'Неверное имя пользователя или пароль.')
            return redirect('login')  # Перенаправление на страницу авторизации в случае ошибки
    else:
        return render(request, 'login.html')

@role_required('admin')
def register(request):
    if request.method == 'POST':
        role = request.POST.get('role')
        user_form = RegistrationForm(request.POST)
        if role == 'teacher':
            teacher_form = TeacherRegistrationForm(request.POST)
            if user_form.is_valid() and teacher_form.is_valid():
                user = user_form.save(commit=False)
                user.set_password(user_form.cleaned_data['password'])
                user.save()

                teacher = teacher_form.save(commit=False)
                teacher.user = user
                teacher.save()

                return redirect('admin_dash')
        elif role == 'parent':
            parent_form = ParentRegistrationForm(request.POST)
            if user_form.is_valid() and parent_form.is_valid():
                user = user_form.save(commit=False)
                user.set_password(user_form.cleaned_data['password'])
                user.save()

                parent = parent_form.save(commit=False)
                parent.user = user
                parent.save()

                return redirect('admin_dash')
        elif role == 'student':
            student_form = StudentRegistrationForm(request.POST)
            if user_form.is_valid() and student_form.is_valid():
                user = user_form.save(commit=False)
                user.set_password(user_form.cleaned_data['password'])
                user.save()

                student = student_form.save(commit=False)
                student.user = user
                student.save()

                return redirect('admin_dash')
    else:
        user_form = RegistrationForm()
        teacher_form = TeacherRegistrationForm()
        parent_form = ParentRegistrationForm()
        student_form = StudentRegistrationForm()
    
    return render(request, 'registration.html', {'user_form': user_form, 'teacher_form': teacher_form, 'parent_form': parent_form, 'student_form': student_form})

def logout_user(request):
    logout(request)
    return redirect('login') 

@role_required('admin')
def admin_dash(request):
    return render(request,'admin.html')

@role_required('admin')
def create_subject(request):
    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_dash')  # Перенаправление на главную страницу администратора после создания предмета
    else:
        form = SubjectForm()
    return render(request, 'admin.html', {'form': form})

@role_required('admin')
def get_subjects(request):
    subjects = Subject.objects.all().values_list('subject_id', 'subject_name')
    subjects_list = [{'id': item[0], 'name': item[1]} for item in subjects]
    return JsonResponse({'subjects': subjects_list})

@role_required('admin')
def get_classes(request):
    classes = Classes.objects.all()
    classes_list = [{'id': cls.class_id, 'name': cls.class_name} for cls in classes]
    return JsonResponse({'classes': classes_list})

@role_required('admin')
def get_parents(request):
    parents = Parent.objects.all()
    parents_list = [{'id': parent.parent_id, 'name': parent.full_name} for parent in parents]
    return JsonResponse({'parents': parents_list})

@role_required('teacher')
def teacher_dash(request):
    return render(request,'teacher_dash.html')

@role_required('student')
def student_dash(request):
    return render(request,'student_dash.html')

@role_required('parent')
def parent_dash(request):
    return render(request,'parent_dash.html')

@role_required('admin')
def schedule_edit(request):
    weekdays = Weekday.objects.all()
    classes = Classes.objects.all()
    schedule_data = []
    for weekday in weekdays:
        schedule_items = Schedule.objects.filter(day_of_week=weekday)
        schedule_data.append((weekday, schedule_items))
    context = {
        'schedule_data': schedule_data,
        'classes': classes,
        'weekdays': weekdays,
    }
    return render(request, 'schedule_edit.html', context)

def rate_view(request, subject_id, class_id):
    subject = Subject.objects.get(pk=subject_id)
    students = Student.objects.filter(class_id=class_id)
    
    if request.method == 'POST':
        form = GradeForm(request.POST)
        if form.is_valid():
            grade = form.cleaned_data['grade']
            date = form.cleaned_data['date']
            student_id = form.cleaned_data['student_id'].pk  # Используйте .id для получения первичного ключа
            student = Student.objects.get(pk=student_id)
            new_grade = Grade(
                grade=grade,
                date=date,
                subject_id=subject,
                student_id=student
            )
            new_grade.save() 
            return redirect('schedule')
    else:
        form = GradeForm(initial={'class_id': class_id})
    
    context = {
        'subject': subject,
        'students': students,
        'form': form,
    }
    return render(request, 'rate.html', context)

gradebook/gradebookprj/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
            color: #007bff;
        }
        .button-container {
            text-align: center;
        }
        .button {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            margin-bottom: 20px;
        }
        .button:hover {
            background-color: #0056b3;
        }
        .user-list {
            list-style-type: none;
            padding: 0;
        }
        .user-item {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f1f1f1;
            border-radius: 3px;
        }
        .user-item:hover {
            background-color: #e6e6e6;
        }
        .user-name {
            font-weight: bold;
            color: #333;
        }
        .logout-button {
            position: absolute;
            top: 10px;
            right: 10px;
            font-size: 15px;
        }
         /* Скрыть модальное окно по умолчанию */
        #myModal {
            display: none;
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(0, 0, 0, 0.4);
        }

        /* Стили для содержимого модального окна */
        .modal-content {
            background-color: #fefefe;
            margin: 15% auto;
            padding: 20px;
            border: 1px solid #888;
            width: 80%;
            max-width: 600px;
            position: relative;
        }

        /* Стили для кнопки закрытия модального окна */
        .close {
            position: absolute;
            right: 10px;
            top: 10px;
            font-size: 20px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Admin Panel</h1>
        <a href="{% url 'logout' %}">
            <button class="logout-button button">Logout</button>
        </a>
            <div class="button-container">
            <!-- Кнопка добавления нового пользователя -->
            <div class="button-container">
                <a href="{% url 'register' %}">
                    <button class="button">Add New User</button>
                </a>
            </div>

            <!-- Кнопка для открытия модального окна -->
            <button class="button" onclick="openModal()">Add New Subject</button>
    
            <!-- Модальное окно для создания нового предмета -->
            <div id="myModal" class="modal">
                <div class="modal-content">
                    <span class="close" onclick="closeModal()">&times;</span>
                    <h2>Create New Subject</h2>
                    <form method="post" action="{% url 'create_subject' %}">
                        {% csrf_token %}
                        <label for="subject_name">Subject Name:</label>
                        <input type="text" id="subject_name" name="subject_name" required>
                        <button type="submit" class="button">Create Subject</button>
                    </form>
                </div>
            </div>
            <div class="button-container">
                <a href="{% url 'schedule' %}">
                    <button class="button">Schedule</button>
                </a>
            </div>
        </div>
        <!-- JavaScript для открытия и закрытия модального окна -->
        <script>
            // Функция для открытия модального окна
            function openModal() {
                document.getElementById('myModal').style.display = 'block';
            }
        
            // Функция для закрытия модального окна
            function closeModal() {
                document.getElementById('myModal').style.display = 'none';
            }
        
            // Закрытие модального окна при клике за его пределами
            window.onclick = function(event) {
                var modal = document.getElementById('myModal');
                if (event.target == modal) {
                    modal.style.display = 'none';
                }
            }
        </script>
    </div>
</body>
</html>

gradebook/gradebookprj/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f1f1f1;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .login-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 3px;
            box-sizing: border-box;
            font-size: 16px; /* изменение размера текста в полях */
        }
        .password-toggle {
            position: relative;
        }
        .password-toggle label {
            cursor: pointer;
            user-select: none;
            position: absolute;
            right: 10px;
            top: 33%;
            transform: translateY(-50%);
            font-size: 25px; /* изменение размера иконки глаза */
        }
        button {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            font-size: 18px;
        }
        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="login-container">
        <h1>Log in to the journal</h1>
        <form method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username" required>
            <div class="password-toggle">
                <input type="password" name="password" id="password" placeholder="Password" required>
                <label for="password" id="toggle-password">&#x1F441;</label>
            </div>
            <button type="submit">Login</button>
        </form>
    </div>

    <script>
        const passwordInput = document.querySelector('#password');
        const togglePassword = document.querySelector('#toggle-password');

        togglePassword.addEventListener('click', function () {
            const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
            passwordInput.setAttribute('type', type);
        });
    </script>
</body>
</html>

gradebook/gradebookprj/templates/parent_dash.html
<h1>U r parent</h1>

gradebook/gradebookprj/templates/rate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Выставление оценок</title>
</head>
<body>
    <h1>Выставление оценок по предмету "{{ subject.subject_name }}"</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить оценку</button>
    </form>
</body>
</html>

gradebook/gradebookprj/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup new user</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f8f9fa;
            font-family: Arial, sans-serif;
        }
        .container {
            max-width: 400px;
            margin: 100px auto;
            padding: 20px;
            border-radius: 5px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .form-group {
            margin-bottom: 5px;
        }
        .form-group label {
            font-weight: bold;
            margin-top: 15px;
        }
        .form-control {
            width: 100%;
            height: 38px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .btn-primary {
            width: 100%;
            padding: 10px;
            border-radius: 4px;
            background-color: #007bff;
            border: 1px solid #007bff;
            color: #fff;
            font-weight: bold;
        }
        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }
        .valid-input {
            background-color: #c3e6cb !important; /* Зеленый цвет при совпадении паролей */
        }
        .invalid-input {
            background-color: #f5c6cb !important; /* Красный цвет при несовпадении паролей */
        }
    </style>
</head>
<body>
    <body>
        <div class="container">
            <h2 class="text-center mb-4">Signup new user</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_role">Role:</label>
                    <select id="id_role" name="role" class="form-control" required onchange="showAdditionalFields()">
                        <option value="teacher">Teacher</option>
                        <option value="student">Student</option>
                        <option value="admin">Admin</option>
                        <option value="parent">Parent</option>
                    </select>
                </div>
                <div class="form-group" id="TeacherFields" style="display: none;">
                    <label for="id_full_name">Full Name:</label>
                    <input type="text" id="full_name" name="full_name" class="form-control">
                    <label for="id_subject">Subject:</label>
                    <select id="id_subject" name="subject" class="form-control">
                        <!-- Здесь можно добавить опции для предметов -->
                    </select>
                    <label for="id_phone_number">Phone Number:</label>
                    <input type="number" id="phone_number" name="phone_number" class="form-control">
                    <label for="id_email">Email:</label>
                    <input type="email" id="email" name="email" class="form-control">
                </div>
                <div class="form-group" id="StudentFields" style="display: none;">
                    <label for="id_full_name">Full Name:</label>
                    <input type="text" id="full_name" name="full_name" class="form-control">
                    <label for="class_id">Class:</label>
                    <select id="class_id" name="class_id" class="form-control">
                        <!-- Опции для классов будут добавлены динамически через JavaScript -->
                    </select>
                    <label for="birth_date">Birth Date:</label>
                    <input type="date" id="birth_date" name="birth_date" class="form-control">
                    <label for="phone_number">Phone Number:</label>
                    <input type="number" id="phone_number" name="phone_number" class="form-control">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" class="form-control">
                    <label for="parent_id">Parent:</label>
                    <select id="parent_id" name="parent_id" class="form-control">
                        <!-- Опции для родителей будут добавлены динамически через JavaScript -->
                    </select>
                </div>
                <div class="form-group" id="ParentFields" style="display: none;">
                    <label for="full_name">Full Name:</label>
                    <input type="text" id="full_name" name="full_name" class="form-control">
                    <label for="phone_number">Phone Number:</label>
                    <input type="number" id="phone_number" name="phone_number" class="form-control">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" class="form-control">
                </div>
                <div class="form-group">
                    <label for="id_username">Username:</label>
                    <input type="text" id="id_username" name="username" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="id_password">Password:</label>
                    <input type="password" id="id_password" name="password" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="id_confirm_password">Confirm password:</label>
                    <input type="password" id="id_confirm_password" name="confirm_password" class="form-control" required>
                    <small id="passwordMatchMessage" class="form-text text-danger"></small>
                </div>
                <button type="submit" class="btn btn-primary">Signup</button>
            </form>
        </div>
        <script>
        var passwordInput = document.getElementById("id_password");
        var confirmPasswordInput = document.getElementById("id_confirm_password");

        confirmPasswordInput.addEventListener("input", function() {
            if (confirmPasswordInput.value === passwordInput.value) {
                confirmPasswordInput.classList.remove("invalid-input");
                confirmPasswordInput.classList.add("valid-input");
                passwordInput.classList.remove("invalid-input");
                passwordInput.classList.add("valid-input");
            } else {
                confirmPasswordInput.classList.remove("valid-input");
                confirmPasswordInput.classList.add("invalid-input");
                passwordInput.classList.remove("valid-input");
                passwordInput.classList.add("invalid-input");
            }
        });

        function showAdditionalFields() {
            var roleSelect = document.getElementById("id_role");
            var teacherFieldsDiv = document.getElementById("TeacherFields");
            var studentFieldsDiv = document.getElementById("StudentFields");
            var parentFieldsDiv = document.getElementById("ParentFields");

            if (roleSelect.value === "teacher") {
                teacherFieldsDiv.style.display = "block";
                studentFieldsDiv.style.display = "none";
                parentFieldsDiv.style.display = "none";
                loadSubjects(); // Загружаем список предметов при выборе роли учителя
            } else if (roleSelect.value === "student") {
                teacherFieldsDiv.style.display = "none";
                studentFieldsDiv.style.display = "block";
                parentFieldsDiv.style.display = "none";
                loadClasses(); // Загружаем список классов при выборе роли студента
                loadParents(); // Загружаем список родителей при выборе роли студента
            } else if (roleSelect.value === "parent") {
                teacherFieldsDiv.style.display = "none";
                studentFieldsDiv.style.display = "none";
                parentFieldsDiv.style.display = "block";
            } else {
                teacherFieldsDiv.style.display = "none";
                studentFieldsDiv.style.display = "none";
                parentFieldsDiv.style.display = "none";
            }
        }

        function loadClasses() {
            var xhr = new XMLHttpRequest();
            xhr.open('GET', '/get_classes/', true);

            xhr.onload = function () {
                if (xhr.status >= 200 && xhr.status < 400) {
                    var data = JSON.parse(xhr.responseText);
                    var classSelect = document.getElementById("class_id");
                    classSelect.innerHTML = ''; // Очищаем текущие опции

                    data.classes.forEach(function(cls) {
                        var option = document.createElement("option");
                        option.value = cls.id;
                        option.text = cls.name;
                        classSelect.appendChild(option);
                    });
                }
            };

            xhr.send();
        }

        function loadParents() {
            var xhr = new XMLHttpRequest();
            xhr.open('GET', '/get_parents/', true);

            xhr.onload = function () {
                if (xhr.status >= 200 && xhr.status < 400) {
                    var data = JSON.parse(xhr.responseText);
                    var parentSelect = document.getElementById("parent_id");
                    parentSelect.innerHTML = ''; // Очищаем текущие опции

                    data.parents.forEach(function(parent) {
                        var option = document.createElement("option");
                        option.value = parent.id;
                        option.text = parent.name;
                        parentSelect.appendChild(option);
                    });
                }
            };

            xhr.send();
        }

        function loadSubjects() {
            var xhr = new XMLHttpRequest();
            xhr.open('GET', '/get_subjects/', true);

            xhr.onload = function () {
                if (xhr.status >= 200 && xhr.status < 400) {
                    var data = JSON.parse(xhr.responseText);
                    var subjectSelect = document.getElementById("id_subject");
                    subjectSelect.innerHTML = ''; // Очищаем текущие опции

                    data.subjects.forEach(function(subject) {
                        var option = document.createElement("option");
                        option.value = subject.id;
                        option.text = subject.name;
                        subjectSelect.appendChild(option);
                    });
                }
            };

            xhr.send();
        }
        
        // Вызов функции при загрузке страницы, чтобы правильно отобразить поля при первоначальном выборе роли
        showAdditionalFields();
    </script>
</body>
</html>

gradebook/gradebookprj/templates/student_dash.html
<h1>U r student</h1>

gradebook/gradebookprj/templates/teacher_dash.html
<h1>U r teacher</h1>